// react/components/src/Button.tsx
import { LoaderCircle } from 'lucide-react'
import type { ComponentProps } from 'react'
import { Button as UiButton } from './components/ui/button'
import { useComponentsTranslation } from './i18n'
import { cn } from './lib/utils'
import './components.css'

/** Platform button: shadcn/ui button with the platform's look. Keep in sync with react-components.d.ts in the remotes. */
export interface ButtonProps extends ComponentProps<typeof UiButton> {
  /** Shows a spinner and the library's own "please wait" text instead of the children. */
  loading?: boolean
}

export default function Button({ loading = false, disabled, className, children, ...props }: ButtonProps) {
  const { t } = useComponentsTranslation()

  return (
    <UiButton
      data-component="reactComponents/Button"
      data-origin="library"
      disabled={disabled || loading}
      className={cn('ui:rounded-full ui:px-5 ui:shadow-sm', className)}
      {...props}
    >
      {loading ? (
        <>
          <LoaderCircle className="ui:animate-spin" /> {t('loading')}
        </>
      ) : (
        children
      )}
    </UiButton>
  )
}

// vue/components/src/Button.vue
<script setup lang="ts">
import PvButton from 'primevue/button'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import './components.css'

/** Platform button. Keep the props in sync with the declaration in the consuming remotes (vue-components.d.ts). */
export interface ButtonProps {
  label: string
  icon?: string
  variant?: 'primary' | 'secondary' | 'danger'
  /** Shows a spinner and the library's own "please wait" text instead of the label. */
  loading?: boolean
}

const props = withDefaults(defineProps<ButtonProps>(), { icon: undefined, variant: 'primary', loading: false })

// The library brings its own texts. The language comes from the shell's vue-i18n instance (shared singleton).
const { t } = useI18n({
  useScope: 'local',
  messages: {
    de: { loading: 'Bitte warten …' },
    en: { loading: 'Please wait …' },
  },
})

const severity = computed(() => (props.variant === 'primary' ? undefined : props.variant === 'danger' ? 'danger' : 'secondary'))
</script>

<template>
  <PvButton
    :label="loading ? t('loading') : label"
    :icon="icon"
    :loading="loading"
    :severity="severity"
    class="ui:rounded-full ui:px-5 ui:shadow-sm"
    data-component="vueComponents/Button"
    data-origin="library"
  />
</template>
