// vue/host/ClientApp/src/components/AppNav.vue
<script setup lang="ts">
import { computed, inject } from 'vue'
import { useI18n } from 'vue-i18n'
import { localized } from '../i18n'
import { frontendKey, groupPages, pagesInOrder, type NavGroup } from '../lib/remotes'
import { adminRole } from '../lib/registry'
import { useAuthStore } from '../stores/auth'

interface NavItem {
  to: string
  label: string
  icon: string
}

const frontend = inject(frontendKey)!
const auth = useAuthStore()
const { t, locale } = useI18n()

const home = computed<NavItem>(() => ({ to: '/', label: t('nav.home'), icon: 'pi pi-home' }))

// Only the start page has no group: every remote names its own, the shell's pages go under "System".
const groups = computed<NavGroup<NavItem>[]>(() => [
  ...groupPages(
    pagesInOrder(frontend)
      .filter((page) => page.showInNav)
      .filter((page) => (page.requiresAuth || page.roles.length ? auth.isAuthenticated && auth.hasAnyRole(page.roles) : true)),
  ).map((group) => ({
    name: group.name,
    pages: group.pages.map((page) => ({ to: page.path, label: localized(page.title, locale.value), icon: page.icon ?? 'pi pi-file' })),
  })),
  {
    name: t('nav.system'),
    pages: [
      { to: '/debug', label: t('nav.debug'), icon: 'pi pi-wrench' },
      ...(auth.isAuthenticated && auth.hasAnyRole([adminRole])
        ? [{ to: '/debug/registry', label: t('nav.registry'), icon: 'pi pi-sitemap' }]
        : []),
    ],
  },
])
</script>

<template>
  <nav :aria-label="t('nav.label')" data-testid="app-nav">
    <ul class="flex flex-col gap-1">
      <li>
        <RouterLink
          :to="home.to"
          class="flex items-center gap-3 rounded-md px-3 py-2 text-sm hover:bg-surface-100 dark:hover:bg-surface-800"
          exact-active-class="bg-primary/10 font-medium text-primary"
        >
          <i :class="home.icon" />
          {{ home.label }}
        </RouterLink>
      </li>
      <li v-for="(group, index) in groups" :key="`${index}-${group.name}`" class="mt-3" data-testid="nav-group">
        <div class="px-3 pb-1 text-xs font-semibold uppercase tracking-wide text-muted-color" aria-hidden="true">
          {{ group.name }}
        </div>
        <ul class="flex flex-col gap-1" :aria-label="group.name">
          <li v-for="item in group.pages" :key="item.to">
            <RouterLink
              :to="item.to"
              class="flex items-center gap-3 rounded-md px-3 py-2 text-sm hover:bg-surface-100 dark:hover:bg-surface-800"
              exact-active-class="bg-primary/10 font-medium text-primary"
            >
              <i :class="item.icon" />
              {{ item.label }}
            </RouterLink>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</template>

// react/host/ClientApp/src/components/AppNav.tsx
import { FileText, House, Network, Shield, Star, Wrench, type LucideIcon } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { NavLink } from 'react-router'
import { useAuth } from '@/auth/AuthContext'
import { localized } from '@/i18n'
import { useFrontend } from '@/lib/frontend'
import { adminRole } from '@/lib/registry'
import { groupPages, type NavGroup } from '@/lib/remotes'
import { cn } from '@/lib/utils'

/** Icons the BFF config may reference by name. Extend as remotes need more. */
export const navIcons: Record<string, LucideIcon> = { house: House, star: Star, shield: Shield, wrench: Wrench, network: Network }

interface NavItem {
  to: string
  label: string
  icon: LucideIcon
}

export function AppNav({ onNavigate }: { onNavigate?: () => void }) {
  const auth = useAuth()
  const { routes } = useFrontend()
  const { t, i18n } = useTranslation()

  const home: NavItem = { to: '/', label: t('nav.home'), icon: House }

  // Only the start page has no group: every remote names its own, the shell's pages go under "System".
  const groups: NavGroup<NavItem>[] = [
    ...groupPages(
      routes
        .filter((page) => page.showInNav)
        .filter((page) =>
          page.requiresAuth || page.roles.length ? auth.user.isAuthenticated && auth.hasAnyRole(page.roles) : true,
        ),
    ).map((group) => ({
      name: group.name,
      pages: group.pages.map((page) => ({
        to: page.path,
        label: localized(page.title, i18n.language),
        icon: navIcons[page.icon ?? ''] ?? FileText,
      })),
    })),
    {
      name: t('nav.system'),
      pages: [
        { to: '/debug', label: t('nav.debug'), icon: Wrench },
        ...(auth.user.isAuthenticated && auth.hasAnyRole([adminRole])
          ? [{ to: '/debug/registry', label: t('nav.registry'), icon: Network }]
          : []),
      ],
    },
  ]

  const link = (item: NavItem) => (
    <NavLink
      to={item.to}
      end
      onClick={onNavigate}
      className={({ isActive }) =>
        cn(
          'flex items-center gap-3 rounded-md px-3 py-2 text-sm hover:bg-accent',
          isActive && 'bg-primary/10 font-medium text-primary',
        )
      }
    >
      <item.icon className="size-4" />
      {item.label}
    </NavLink>
  )

  return (
    <nav aria-label={t('nav.label')} data-testid="app-nav">
      <ul className="flex flex-col gap-1">
        <li>{link(home)}</li>
        {groups.map((group, index) => (
          <li key={`${index}-${group.name}`} className="mt-3" data-testid="nav-group">
            <div className="px-3 pb-1 text-xs font-semibold tracking-wide text-muted-foreground uppercase" aria-hidden="true">
              {group.name}
            </div>
            <ul className="flex flex-col gap-1" aria-label={group.name}>
              {group.pages.map((item) => (
                <li key={item.to}>{link(item)}</li>
              ))}
            </ul>
          </li>
        ))}
      </ul>
    </nav>
  )
}
