// react/host/ClientApp/src/components/DevOverrideBanner.tsx
import { TriangleAlert } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router'
import { Button } from '@/components/ui/button'
import { clearOverrides } from '@/lib/devOverrides'
import { useFrontend } from '@/lib/frontend'

/** Always visible while an override is active: a page from the developer's machine must not pass for the stage's. */
export function DevOverrideBanner() {
  const { config } = useFrontend()
  const { t } = useTranslation()
  const active = Object.entries(config.overrides ?? {})
  if (!active.length) return null

  const reset = () => {
    clearOverrides()
    window.location.reload()
  }

  return (
    <div
      role="status"
      className="flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-amber-300 bg-amber-50 px-4 py-2 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100"
      data-origin="host"
      data-testid="dev-override-banner"
    >
      <TriangleAlert className="size-4" />
      <span className="font-medium">{t('overrides.banner.text')}</span>
      {active.map(([id, override]) => (
        <span key={id} className="break-all" data-testid="dev-override-item">
          {id}
          {override.entry && ` · ${t('overrides.banner.ui')} ${override.entry}`}
          {override.api && ` · ${t('overrides.banner.api')} ${override.api}`}
        </span>
      ))}
      <span className="ml-auto flex items-center gap-2">
        <Link to="/debug/overrides" className="underline-offset-2 hover:underline">
          {t('overrides.banner.settings')}
        </Link>
        <Button variant="ghost" size="sm" onClick={reset} data-testid="dev-override-reset">
          {t('overrides.banner.reset')}
        </Button>
      </span>
    </div>
  )
}

// vue/host/ClientApp/src/components/DevOverrideBanner.vue
<script setup lang="ts">
import Button from 'primevue/button'
import Message from 'primevue/message'
import { computed, inject } from 'vue'
import { useI18n } from 'vue-i18n'
import { clearOverrides } from '../lib/devOverrides'
import { frontendKey } from '../lib/remotes'

const frontend = inject(frontendKey)!
const { t } = useI18n()

// Always visible while an override is active: a page from the developer's machine must not pass for the stage's.
const active = computed(() => Object.entries(frontend.overrides ?? {}))

function reset(): void {
  clearOverrides()
  window.location.reload()
}
</script>

<template>
  <Message v-if="active.length" severity="warn" :closable="false" class="rounded-none" data-origin="host" data-testid="dev-override-banner">
    <div class="flex flex-wrap items-center gap-x-3 gap-y-1">
      <span class="font-medium">{{ t('overrides.banner.text') }}</span>
      <span v-for="[id, override] in active" :key="id" class="break-all" data-testid="dev-override-item">
        {{ id }}
        <template v-if="override.entry">· {{ t('overrides.banner.ui') }} {{ override.entry }}</template>
        <template v-if="override.api">· {{ t('overrides.banner.api') }} {{ override.api }}</template>
      </span>
      <span class="ml-auto flex gap-2">
        <RouterLink to="/debug/overrides" class="underline-offset-2 hover:underline">{{ t('overrides.banner.settings') }}</RouterLink>
        <Button :label="t('overrides.banner.reset')" size="small" severity="warn" text data-testid="dev-override-reset" @click="reset" />
      </span>
    </div>
  </Message>
</template>
