// react/host/ui/src/components/AppHeader.tsx
import { LayoutGrid, LogIn, LogOut, Menu, Moon, Sun, User } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useLocation } from 'react-router'
import { useAuth } from '@/auth/AuthContext'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { LanguageSwitcher } from './LanguageSwitcher'

export function AppHeader({ onToggleNav }: { onToggleNav: () => void }) {
  const auth = useAuth()
  const location = useLocation()
  const { t } = useTranslation()
  const [dark, setDark] = useState(() => document.documentElement.classList.contains('dark'))

  const toggleDark = () => setDark(document.documentElement.classList.toggle('dark'))

  return (
    <header className="flex h-14 items-center gap-3 border-b bg-card px-4" data-testid="app-header" data-origin="host">
      <Button variant="ghost" size="icon" className="md:hidden" aria-label={t('nav.open')} onClick={onToggleNav}>
        <Menu />
      </Button>
      <Link to="/" className="flex items-center gap-2 font-semibold">
        <LayoutGrid className="size-5 text-primary" />
        <span>
          {t('app.name')} <span className="text-muted-foreground">· {t('app.variant')}</span>
        </span>
      </Link>

      <div className="ml-auto flex items-center gap-2">
        <LanguageSwitcher />
        <Button variant="ghost" size="icon" aria-label={dark ? t('header.lightMode') : t('header.darkMode')} onClick={toggleDark}>
          {dark ? <Sun /> : <Moon />}
        </Button>
        {auth.user.isAuthenticated ? (
          <>
            <span className="hidden items-center gap-2 text-sm sm:flex" data-testid="user-info">
              <User className="size-4 text-muted-foreground" />
              <span data-testid="user-name">{auth.user.name}</span>
              {auth.user.roles.map((role) => (
                <Badge key={role} variant="secondary">
                  {role}
                </Badge>
              ))}
            </span>
            <Button variant="secondary" size="sm" onClick={auth.logout}>
              <LogOut /> {t('header.logout')}
            </Button>
          </>
        ) : (
          auth.loaded && (
            <Button size="sm" onClick={() => auth.login(location.pathname + location.search)}>
              <LogIn /> {t('header.login')}
            </Button>
          )
        )}
      </div>
    </header>
  )
}

// vue/host/ui/src/components/AppHeader.vue
<script setup lang="ts">
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import LanguageSwitcher from './LanguageSwitcher.vue'

defineEmits<{ 'toggle-nav': [] }>()

const auth = useAuthStore()
const route = useRoute()
const { t } = useI18n()

const dark = ref(document.documentElement.classList.contains('app-dark'))
function toggleDark() {
  dark.value = document.documentElement.classList.toggle('app-dark')
}
</script>

<template>
  <header
    class="flex h-14 items-center gap-3 border-b border-surface-200 bg-surface-0 px-4 dark:border-surface-800 dark:bg-surface-900"
    data-testid="app-header"
    data-origin="host"
  >
    <Button icon="pi pi-bars" text rounded class="md:hidden" :aria-label="t('nav.open')" @click="$emit('toggle-nav')" />
    <RouterLink to="/" class="flex items-center gap-2 font-semibold">
      <i class="pi pi-th-large text-primary" />
      <span>{{ t('app.name') }} <span class="text-muted-color">· {{ t('app.variant') }}</span></span>
    </RouterLink>

    <div class="ml-auto flex items-center gap-2">
      <LanguageSwitcher />
      <Button
        :icon="dark ? 'pi pi-sun' : 'pi pi-moon'"
        text
        rounded
        :aria-label="dark ? t('header.lightMode') : t('header.darkMode')"
        @click="toggleDark"
      />
      <template v-if="auth.isAuthenticated">
        <span class="hidden items-center gap-2 sm:flex" data-testid="user-info">
          <i class="pi pi-user text-muted-color" />
          <span data-testid="user-name">{{ auth.user.name }}</span>
          <Tag v-for="role in auth.user.roles" :key="role" :value="role" severity="secondary" />
        </span>
        <Button :label="t('header.logout')" icon="pi pi-sign-out" severity="secondary" size="small" @click="auth.logout()" />
      </template>
      <Button
        v-else-if="auth.loaded"
        :label="t('header.login')"
        icon="pi pi-sign-in"
        size="small"
        @click="auth.login(route.fullPath)"
      />
    </div>
  </header>
</template>
